version: "3.3"
services:
  discord-loc:
    image: tokenshift/discord-loc:latest
    env_file: ./discord-loc/.env
    volumes:
      - ./volumes/discord-loc:/data
  discord-mistbot:
    image: tokenshift/discord-mistbot:latest
    env_file: ./discord-mistbot/.env
    volumes:
      - ./volumes/discord-mistbot:/data
  discord-mockingbird:
    image: tokenshift/discord-mockingbird:latest
    env_file: ./discord-mockingbird/.env
    volumes:
      - ./volumes/discord-mockingbird:/data
